### ISSUE TITLE
Making-Websites-With-October-CMS

### ISSUE THREAD

**Issue by arthurrc03** [ivandoric/Making-Websites-With-October-CMS#3]
Hi,

I neep help you...

How can display row, when create plugin with builder plugin.

this is displayColum. 
I would like to do this by showing all the columns in a row.

{% for record in records %}
        <li>{{ attribute(record, displayColumn) }}</li>
    {% endfor %}

Regards.

**Comment by ivandoric** [comment]
Please check this episode out: https://www.youtube.com/watch?v=Ukcf8tgQUXc it will make it much easier to display data then using a component.

**Comment by arthurrc03** [comment]
Hi,

thanks you for your response.

Cómo evitar el cuadro de dialogos, que se genera cuando pulsas submit en el formulario? (october cms ajax validation 25)

regards

**Comment by ivandoric** [comment]
What dialog box?

**Comment by arthurrc03** [comment]
Good morning,

episode 25 in the minute 6:30 appears one additional dialogs. how to avoid this, for the clients when submit form.

Regards.

**Comment by ivandoric** [comment]
Did you check out the video till the end?

**Comment by arthurrc03** [comment]
Yes, I can't detected the error. Sorry!

**Comment by ivandoric** [comment]
What I'm trying to say is that the final product doesn't have any dialog boxes. At least for Ajax validation.

**Comment by arthurrc03** [comment]
additional dialog ('the name filed is required'). 
Can only be disabled with the checkbox?

**Comment by ivandoric** [comment]
There is no additional dialog. Watch the video to the end. The thing on 6:30 was just an example.

**Comment by arthurrc03** [comment]
Is there any form to reset the form after sending with ajax?

**Comment by andrehol** [comment]
In the video Making Websites With October CMS - Part 13 - I have get this issue: **The partial '_field_castbox.htm' is not found.** 

Only difference between your code and mine it's  I change the name actorbox to castbox, just for hold previous actor in Part 12 video untouched.

**Comment by ivandoric** [comment]
Stupid question, but is there a file called _field_actorbox.htm :) in your install? If there is, is it in the right place? If the answer to both this questions is yes, then try to download files from that episode and see if that works: https://github.com/ivandoric/Making-Websites-With-October-CMS/releases/tag/13

**Comment by cocodrino** [comment]
I'm getting the same error as @andrehol, I created the form widget using artisan

     php artisan create:formwidget yo.movies ActorBox

this created a partial in the following path
       <my_installation>/plugins/yo/movies/formwidgets/actorbox/partials/_actorbox.htm

I've tried renaming the file  **_actorbox.htm** to **_field_actorbox.htm** but this doesnt works neither

running xdebug I notice something interesting, I put a breakpoint in the line 87 of ViewMaker.php

      $partialPath = $this->getViewPath($partial);

In the others loading partials this $partialPath takes the absolute path

     "/opt/lampp/htdocs/october1/install-master/modules/backend/widgets/form/partials/_form.htm"
     "/opt/lampp/htdocs/october1/install-master/modules/backend/widgets/form/partials/_form_fields.htm"

and so one...but with this partial the $partialPath is "_field_actorbox.htm"...so this just include the name file, not the path

and the full error is

     Uncaught October\Rain\Exception\SystemException: The partial '_field_actorbox.htm' is not found. in /opt/lampp/htdocs/october1/install-master/modules/system/traits/ViewMaker.php:94 Stack trace: #0 /opt/lampp/htdocs/october1/install-master/modules/backend/widgets/Form.php(273): Backend\Classes\WidgetBase->makePartial('_field_actorbox...', Array) #1 /opt/lampp/htdocs/october1/install-master/modules/backend/widgets/form/partials/_field.htm(22): Backend\Widgets\Form->renderFieldElement(Object(Backend\Classes\FormField)) #2 /opt/lampp/htdocs/october1/install-master/modules/system/traits/ViewMaker.php(247): include('/opt/lampp/htdo...') #3 /opt/lampp/htdocs/october1/install-master/modules/system/traits/ViewMaker.php(101): Backend\Classes\WidgetBase->makeFileContents('/opt/lampp/htdo...', Array) #4 /opt/lampp/htdocs/october1/install-master/modules/backend/widgets/form/partials/_field-container.htm(8): Backend\Classes\WidgetBase->makePartial('_field.htm', Array) #5 /opt/lampp/htdocs/october1/install-master/modules/sy 

hope than you can know a possible solution for this...thank you!!!

**Comment by ivandoric** [comment]
@cocodrino Did you try to download the files for that lesson from github, and then work from there? Honestly these problems are usually because of some syntax error, or you missed somethng etc. try downloading my code and see if that works for you.

**Comment by marcomessa** [comment]
Same problem here, tried also with your files but no luck. I solved it adding this in fields.yaml


`actors:
        label: Actors
        span: left
        type: Mmes\Movies\FormWidgets\Actorbox`

Found this here
https://github.com/octobercms/october/issues/1211

**Comment by LostArk2018** [comment]
> 
> 
> In the video Making Websites With October CMS - Part 13 - I have get this issue: **The partial '_field_actorbox.htm' is not found.**

In my case, problem was caused by incorrect directory for file Actorbox.php.  It was placed here: formwidgets/actorbox/Actorbox.php    while it should be here:   formwidgets/Actorbox.php
